### ISSUE TITLE
nbformat.corpus module not found

### ISSUE THREAD

**Issue by ellielai** [CMU-MS-DAS-Modern-Programming-Mini/ClassAssignmentNo4#1]
When I type in 'jupyter notebook' to try to open the notebook, this is the call I get back:

Traceback (most recent call last):
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/lib/python3.8/site-packages/notebook/notebookapp.py", line 80, in <module>
    from .services.contents.manager import ContentsManager
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/lib/python3.8/site-packages/nbformat/__init__.py", line 16, in <module>
    from . import v4
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/lib/python3.8/site-packages/nbformat/v4/__init__.py", line 10, in <module>
    from .nbbase import (
  File "/mnt/c/Users/ellie.DESKTOP-1LQF5GM/ClassAssignmentNo4/venv/lib/python3.8/site-packages/nbformat/v4/nbbase.py", line 13, in <module>
    from ..corpus.words import generate_corpus_id as random_cell_id
ModuleNotFoundError: No module named 'nbformat.corpus'

I'm pretty sure all the requirements installed correctly. I tried just re-installing nbformat using pip as well but that also didn't work. I also tried 'python3 -m notebook' which gave the same error. I'm so sorry for all the technical issues :/

**Comment by shots47s** [comment]
You set up the virtualenv and activated it, then installed?

**Comment by shots47s** [comment]
oh wait, nevermind, I see that you did. hang on, looking into it, I tried this on WSL and it worked fine.

**Comment by shots47s** [comment]
Ah... do me a favor, in your virtual envorinment, do:

`pip install notebook`

And see if that fixes it.

**Comment by shots47s** [comment]
hmm, ok, I can't reproduce it on my rig, so I will need to look at your setup, can we look at it tomorrow at the beginning of class?

**Comment by ellielai** [comment]
Yes, that would be great

**Comment by ellielai** [comment]
So I just deleted my venv and created a new one and re-did all the installation steps, which I think worked. There were quite a few readouts that I didn't know if they were bad or good, so I may just verify that everything looks okay tomorrow before class.
